name: my first test
on: push
jobs:
  my-first-real-action:
    runs-on: ubuntu-latest
    
    steps:

      - name: CheckOut library
        uses: actions/checkout@v3
      - run: echo "aboba boba"
      - name: Install
        # uses: actions/checkout@v3
        run: npm install
      - name: test
        # uses: actions/checkout@v3
        run: npm run test
      - name: build
        run: npm run build
      # - name: start
      #   run: npm start
